travis:
  secure:
    BINSTAR_TOKEN: z5u1sz2WZJRB2COGz3eSddUkz5i7Wad6nqdR6J6BwGx0nWVuId7kQjoOVBa0XM2YBhsvsV8fpTC4SHgcERN3jEqCOW+0SiRqZiSk35NTTay97AK17XtUEImI/65czZE2SuSosLfgLgZn06SiDxQo9Y6ZbORyszbL3uKkx07OVha93UrmwxWm6Q88wH+SrElgp5yGk8BgIdx+4uJvoTT+PIfGhP78gqNecET/zKynWFBnFEWxckIswDOL1+RoFkKF2atCdIUZs6vSy5inFGX1M6Zn+iRrgkY4U9/boLeZ/St0xPymrg2dTTmoWy8/FMJeGZOit+v19DukpAiJvYoXVzFwM1Bc/Zk2mQfSLXPNuWQB4BK/SP3o7KS1QHNsgaO6PcZ6TWmz3rM3Emr+WGfGjjSEdPfeBl4lSx0Zn+N7rUUvYQWHRdijCq5dqOfnsCeh6wyeoQ2rF9ar1rXWPnt892sOadKvtAEv4nl2cc1gP1NI2EMqHUQJWj1A++zWJht9LG3nh5BRFo1RgkV0RHYefOT/1H492DdMGkF42O17Ti0uIbPP8hWutk24N0YGqogm8DmBx2JHk9nMzSPTQHGFDP3z7tiGmjkK5aKPuxpPENvGg4uXieIEQ2XXeX78p6zwXDET+LZAwSQtr/zCVwCyNyr95TrKbzUf8K0FcxFBsVM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
